 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
100.38.69.168 - - [10/Aug/2020 18:11:25] "[37mPOST /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:11:30] "[37mPOST /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:11:35] "[37mPOST /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:11:40] "[37mPOST /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:11:50] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:11:50] "[37mPOST /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:11:55] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:11:55] "[37mPOST /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:12:14] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:12:15] "[37mPOST /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:23:38] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:23:39] "[37mPOST /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:45:05] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:45:05] "[37mPOST /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:47:55] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:47:55] "[37mPOST /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:48:05] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:48:05] "[35m[1mPOST /api HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/apps/eigen-project/app.py", line 19, in findWords
    res = router.extractWords(files)
  File "/root/apps/eigen-project/routes/router.py", line 41, in extractWords
    raise Exception('Number of documents must be greater than 1')
Exception: Number of documents must be greater than 1
100.38.69.168 - - [10/Aug/2020 18:48:16] "[35m[1mPOST /api HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/apps/eigen-project/app.py", line 19, in findWords
    res = router.extractWords(files)
  File "/root/apps/eigen-project/routes/router.py", line 41, in extractWords
    raise Exception('Number of documents must be greater than 1')
Exception: Number of documents must be greater than 1
100.38.69.168 - - [10/Aug/2020 18:48:29] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:48:29] "[35m[1mPOST /api HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/apps/eigen-project/app.py", line 19, in findWords
    res = router.extractWords(files)
  File "/root/apps/eigen-project/routes/router.py", line 41, in extractWords
    raise Exception('Number of documents must be greater than 1')
Exception: Number of documents must be greater than 1
100.38.69.168 - - [10/Aug/2020 18:49:20] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 18:49:20] "[37mPOST /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 19:09:52] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [10/Aug/2020 19:09:52] "[37mPOST /api HTTP/1.1[0m" 200 -
83.97.20.29 - - [10/Aug/2020 21:58:59] code 400, message Bad request syntax ('\x00\x00\x00¬§√øSMBr\x00\x00\x00\x00\x08\x01@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x06\x00\x00\x01\x00\x00\x81\x00\x02PC NETWORK PROGRAM 1.0\x00\x02MICROSOFT NETWORKS 1.03\x00\x02MICROSOFT NETWORKS 3.0\x00\x02LANMAN1.0\x00\x02LM1.2X002\x00\x02Samba\x00\x02NT LANMAN 1.0\x00\x02NT LM 0.12\x00')
83.97.20.29 - - [10/Aug/2020 21:58:59] "[35m[1m   ¬§√øSMBr    @              @    ¬Å PC NETWORK PROGRAM 1.0 MICROSOFT NETWORKS 1.03 MICROSOFT NETWORKS 3.0 LANMAN1.0 LM1.2X002 Samba NT LANMAN 1.0 NT LM 0.12 [0m" HTTPStatus.BAD_REQUEST -
83.97.20.29 - - [10/Aug/2020 21:58:59] "[33mGET / HTTP/1.1[0m" 404 -
100.38.69.168 - - [11/Aug/2020 04:21:24] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [11/Aug/2020 04:21:24] "[37mPOST /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [11/Aug/2020 04:21:46] "[35m[1mPOST /api HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/apps/eigen-project/app.py", line 19, in findWords
    res = router.extractWords(files)
  File "/root/apps/eigen-project/routes/router.py", line 41, in extractWords
    raise Exception('Number of documents must be greater than 1')
Exception: Number of documents must be greater than 1
100.38.69.168 - - [11/Aug/2020 04:21:52] "[37mPOST /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [11/Aug/2020 04:22:12] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [11/Aug/2020 04:22:12] "[37mPOST /api HTTP/1.1[0m" 200 -
80.0.167.215 - - [11/Aug/2020 11:25:29] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
80.0.167.215 - - [11/Aug/2020 11:25:30] "[35m[1mPOST /api HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/apps/eigen-project/app.py", line 19, in findWords
    res = router.extractWords(files)
  File "/root/apps/eigen-project/routes/router.py", line 41, in extractWords
    raise Exception('Number of documents must be greater than 1')
Exception: Number of documents must be greater than 1
80.0.167.215 - - [11/Aug/2020 11:39:01] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
80.0.167.215 - - [11/Aug/2020 11:39:02] "[35m[1mPOST /api HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/apps/eigen-project/app.py", line 19, in findWords
    res = router.extractWords(files)
  File "/root/apps/eigen-project/routes/router.py", line 41, in extractWords
    raise Exception('Number of documents must be greater than 1')
Exception: Number of documents must be greater than 1
100.38.69.168 - - [11/Aug/2020 11:59:46] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
100.38.69.168 - - [11/Aug/2020 11:59:47] "[37mPOST /api HTTP/1.1[0m" 200 -
185.173.35.61 - - [11/Aug/2020 16:03:41] "[33mGET / HTTP/1.1[0m" 404 -
80.0.167.215 - - [11/Aug/2020 17:11:37] "[37mOPTIONS /api HTTP/1.1[0m" 200 -
80.0.167.215 - - [11/Aug/2020 17:11:38] "[37mPOST /api HTTP/1.1[0m" 200 -
209.17.96.42 - - [11/Aug/2020 18:17:15] "[33mGET / HTTP/1.1[0m" 404 -
54.164.188.252 - - [11/Aug/2020 19:09:04] code 400, message Bad request syntax ('\x16\x03\x01\x00¬º\x01\x00\x00¬∏\x03\x03¬ª\x0bEZ\x93;\\*√ÑN\x0b\x9a8s√¨V¬∞√¶\x100√å¬§\x86wM`7√∂1W√¶\x0c \x05N\x1d¬∏√¨√è¬∏5\x95\x8c√í√∫√Ç\x1d]\x9f¬™;\x1cc(√õ√íH_√õc√£√Ä`3A\x00 √Ä/√Ä0√Ä+√Ä,√å¬®√å¬©√Ä\x13√Ä\t√Ä\x14√Ä')
54.164.188.252 - - [11/Aug/2020 19:09:04] "[35m[1m ¬º  ¬∏¬ªEZ¬ì;\*√ÑN¬ö8s√¨V¬∞√¶0√å¬§¬ÜwM`7√∂1W√¶ N¬∏√¨√è¬∏5¬ï¬å√í√∫√Ç]¬ü¬™;c(√õ√íH_√õc√£√Ä`3A  √Ä/√Ä0√Ä+√Ä,√å¬®√å¬©√Ä√Ä	√Ä√Ä[0m" HTTPStatus.BAD_REQUEST -
92.118.161.1 - - [11/Aug/2020 20:04:47] "[33mGET / HTTP/1.0[0m" 404 -
222.186.61.115 - - [12/Aug/2020 02:09:15] "[33mCONNECT ip.ws.126.net:443 HTTP/1.1[0m" 404 -
209.17.97.66 - - [12/Aug/2020 03:43:29] "[33mGET / HTTP/1.1[0m" 404 -
83.97.20.29 - - [12/Aug/2020 05:47:34] code 400, message Bad request syntax ('\x00\x00\x00¬§√øSMBr\x00\x00\x00\x00\x08\x01@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x06\x00\x00\x01\x00\x00\x81\x00\x02PC NETWORK PROGRAM 1.0\x00\x02MICROSOFT NETWORKS 1.03\x00\x02MICROSOFT NETWORKS 3.0\x00\x02LANMAN1.0\x00\x02LM1.2X002\x00\x02Samba\x00\x02NT LANMAN 1.0\x00\x02NT LM 0.12\x00')
83.97.20.29 - - [12/Aug/2020 05:47:34] "[35m[1m   ¬§√øSMBr    @              @    ¬Å PC NETWORK PROGRAM 1.0 MICROSOFT NETWORKS 1.03 MICROSOFT NETWORKS 3.0 LANMAN1.0 LM1.2X002 Samba NT LANMAN 1.0 NT LM 0.12 [0m" HTTPStatus.BAD_REQUEST -
83.97.20.29 - - [12/Aug/2020 05:47:35] "[33mGET / HTTP/1.1[0m" 404 -
185.202.1.204 - - [12/Aug/2020 09:22:00] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*√†\x00\x00\x00\x00\x00Cookie:')
185.202.1.204 - - [12/Aug/2020 09:22:00] "[35m[1m  /*√†     Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
178.32.197.80 - - [12/Aug/2020 10:44:30] "[33mGET / HTTP/1.1[0m" 404 -
209.17.96.106 - - [12/Aug/2020 17:39:40] "[33mGET / HTTP/1.1[0m" 404 -
Traceback (most recent call last):
  File "/root/apps/eigen-project/app.py", line 7, in <module>
    import router
  File "./routes/router.py", line 106
    sd = getStandardDev(count)
                             ^
TabError: inconsistent use of tabs and spaces in indentation
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
98.221.172.112 - - [12/Aug/2020 23:16:53] "[37mPOST /api HTTP/1.1[0m" 200 -
98.221.172.112 - - [12/Aug/2020 23:18:08] "[37mPOST /api HTTP/1.1[0m" 200 -
